#!/usr/bin/expect -f

set timeout 30
spawn ssh root@47.117.176.214
expect {
    "yes/no" {
        send "yes\r"
        exp_continue
    }
    "password:" {
        send "0212Connect!\r"
    }
}

expect "# "
send "firewall-cmd --zone=public --add-port=3001/tcp --permanent\r"
expect "# "
send "firewall-cmd --reload\r"
expect "# "
send "firewall-cmd --list-ports\r"
expect "# "
send "exit\r"
expect eof